### ISSUE TITLE
Webpack loaders issue

### ISSUE THREAD

**Issue by lagamura** [ghalex/vue3-charts#16]
Hello, I am a beginner with vue 3, i have the following problem with vue3-charts after npm run serve:

My dependencies:
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^3.0.0",
    "vue-slider-component": "^4.0.0-beta.4",
    "vue3-charts": "^1.1.22"
  },

The Error:
`in ./node_modules/vue3-charts/dist/vue3-charts.esm.js

Module parse failed: Unexpected token (6533:20)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loadersepts#loaders
|       ]),
|       createElementVNode("g", _hoisted_4$3, [
>         (!_ctx.axis?.primary?.hide)
|           ? (openBlock(), createBlock(_component_axis, {
|               key: 0,
                                                                                                                                                      /vue-loader-v16/dist??ref--0-1!./sr
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js 2:0-32 7:11-16
 @ ./src/App.vue?vue&type=script&lang=js
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.14:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js`

**Comment by ghalex** [comment]
What is the setup? Simple vue-cli setup or you guys are using custom webpack file?

**Comment by sangyoo91** [comment]
Same here, just using Vue3 cli

**Comment by Pin0** [comment]
Yes same issue using @vue/cli 4.5.15 yarn 1.22.10 and node v14.18.0

**Comment by pvanagtmaal** [comment]
Please see my [comment](https://github.com/ghalex/vue3-charts/issues/19#issuecomment-996073899) for a fix (I'm not using webpack anymore but this used to work for me)

**Comment by ghalex** [comment]
This is fixed in version 1.1.27.
