### ISSUE TITLE
Pie Chart can't have more than 7 data

### ISSUE THREAD

**Issue by mpalencia** [ghalex/vue3-charts#22]
Try to use 10 elements of an array on a pie chart. It will display only 7.

**Comment by ghalex** [comment]
Maybe @pvanagtmaal can help here, he was the one developing the Pie chart.

**Comment by mpalencia** [comment]
Closing this, tested it will work on several data, more than 7, but will not work if a data is the same with other values.
New ticket:
https://github.com/ghalex/vue3-charts/issues/24

Thanks mate!
