### ISSUE TITLE
typescript types declarations

### ISSUE THREAD

**Issue by ralpheichelberger** [ghalex/vue3-charts#25]
Thank you for a simple way to display charts! That is awsome!

Could you please provide "@types/vue3-charts", so one can build with vite vue/ts, please!

**Comment by ghalex** [comment]
Hi @ralpheichelberger,

The library is written in typescript and provides typing, check your node_modules you 
will find `vue3-charts/dist/index.d.ts`.

Thanks,
Alexandru
