### ISSUE TITLE
If external container size is defined by display: grid, lower axis ticks dissapear

### ISSUE THREAD

**Issue by baybal** [ghalex/vue3-charts#4]
https://gist.github.com/baybal/bf3ba9037ba2719ec4b39fe1226e3874

**Comment by ghalex** [comment]
Can you provide a sandbox example like this one:
https://codesandbox.io/s/vue3-charts-example-14mmp

So I can check what is the problem. I personally use it with "display: grid" and works fine for me.

**Comment by baybal** [comment]
> Can you provide a sandbox example like this one:
> https://codesandbox.io/s/vue3-charts-example-14mmp
> 
> So I can check what is the problem. I personally use it with "display: grid" and works fine for me.

https://codesandbox.io/s/vue3-charts-example-forked-ohwod

**Comment by baybal** [comment]
@ghalex I was debugging this. The size of the canvas becomes negative for some unfathomable reason if I use responsive.

![Screenshot_2021-09-01_06-57-19](https://user-images.githubusercontent.com/3344988/131581130-377093b3-c6ce-42d2-aece-2ac1ffdcc88d.png)

**Comment by baybal** [comment]
I believe it's because canvas size goes to 0 at the very beginning, before CSS grid starting pushing back
