### ISSUE TITLE
Is it normal that datapoints past domain boundary are rendered outside of the graph area?

### ISSUE THREAD

**Issue by baybal** [ghalex/vue3-charts#5]
![image](https://user-images.githubusercontent.com/3344988/118148944-dfbcf800-b432-11eb-8e55-6271ce2ac293.png)

**Comment by ghalex** [comment]
I have recreated your example here:
https://codesandbox.io/s/vue3-charts-example-14mmp

I think it has something to do with the `domain` of the primary axes. I use a `band` scale for dates and then provide `tickValues` prop to show a nicer axis, but your example should work too.

I will take a look at why the domain is not correctly calculated and get back with an answer.
