### ISSUE TITLE
feature request: hiding axis

### ISSUE THREAD

**Issue by michaelowens** [ghalex/vue3-charts#8]
Hi,

Would love to see an option to hide the x and/or y axis, leaving the entire canvas available for just the bar/line. This is useful when using the chart as a background or if it's more for a visual representation of change rather than hard numbers.

Thanks in advance!

**Comment by ghalex** [comment]
Hi @michaelowens,

You are right this is a useful feature. I will consider this but until then you can use chart margin to hide the axis:

```javascript
const margin = ref({
      left: -41,
      top: 0,
      right: -1,
      bottom: 20
 })
```

This can give you a chart [like this](https://www.dropbox.com/s/h94914bbssxm6vh/Screenshot%202021-07-23%20at%2010.36.41.png?dl=0)

**Comment by ghalex** [comment]
Version 1.1.20 now has the ability to hide axis:

```js
const axis = ref({
  primary: {
    hide: true
  },
  secondary: {
    hide: true
  }
})
```
