### ISSUE TITLE
feature request: option for gap

### ISSUE THREAD

**Issue by michaelowens** [ghalex/vue3-charts#9]
Hi,

I can't seem to find a way to change the gap between bars.

I noticed there is a `gap` variable in `useBars` which is hardcoded to 5. It would be nice to see this configurable to change the spacing between bars. For smaller charts 5 is quite a lot and causes you to have tiny bars.

For example using the default:
![image](https://user-images.githubusercontent.com/647632/126786474-267b027c-4641-4fbb-a326-526e3c5ef360.png)

But when I change the built js file to have `gaps` set to 1.5:
![image](https://user-images.githubusercontent.com/647632/126786400-24f7d907-38c0-4d59-9a12-0ea2f5b8df1f.png)

Thanks in advance! Loving the library.

**Comment by ghalex** [comment]
Version 1.1.20 has the ability to change the gap:

```vue
<Bar
  :dataKeys="['name', 'avg']"
  :barStyle="{ fill: '#0096c7' }"
  :gap="0" // set gap here
/>
```
